apiVersion: v2
name: magda-minion-linked-data-rating
description: A Helm chart for Magda Linked Data Rating Minion
version: "1.0.0-alpha.0"
kubeVersion: ">= 1.14.0-0"
home: "https://github.com/magda-io/magda-minion-linked-data-rating"
sources:
  [
    "https://github.com/magda-io/magda-minion-linked-data-rating"
  ]
